DEBUG 2017-01-02 10:45:49,392: 	 Executing command: 'submit'
DEBUG 2017-01-02 10:45:49,392: 	 Found CRAB cache file /afs/cern.ch/user/h/hkaveh/.crab3
DEBUG 2017-01-02 10:45:49,401: 	 Checking credentials
DEBUG 2017-01-02 10:45:49,404: 	 Found proxy file /tmp/x509up_u98267
DEBUG 2017-01-02 10:45:49,404: 	 Getting proxy life time left
DEBUG 2017-01-02 10:45:50,110: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u98267 -timeleft
 output : 38812

 error: 
 retcode : 0
DEBUG 2017-01-02 10:45:50,626: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u98267 -actimeleft
 output : 38812

 error: 
 retcode : 0
DEBUG 2017-01-02 10:45:50,626: 	 Proxy valid for 10:46:52 hours
INFO 2017-01-02 10:45:50,626: 	 Will use CRAB configuration file crabConfigMC.py
DEBUG 2017-01-02 10:45:50,627: 	 Loading CRAB configuration file.
DEBUG 2017-01-02 10:45:50,633: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2017-01-02 10:45:50,634: 	 Working area '/afs/cern.ch/work/h/hkaveh/workarea/CMSSW_8_0_20/src/whelicity1/MiniAnalyzer/test/crab_projects/crab_tutorial_May2015_MC_analysis' already exists 
Please change the requestName in the config file
ERROR 2017-01-02 10:45:50,634: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp3/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp3/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp3/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp3/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1611-comp3/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/h/hkaveh/workarea/CMSSW_8_0_20/src/whelicity1/MiniAnalyzer/test/crab_projects/crab_tutorial_May2015_MC_analysis' already exists 
Please change the requestName in the config file
